name: "Check commits"

on: pull_request

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: "Check commits"
      uses: muzimuzhi/actions/dco-check@skip-dependabot-commits
      with:
        base_ref: ${{ github.base_ref }}
        allow_co-authored: true
